packages:
  - website/
  - packages/*

onlyBuiltDependencies:
  - '@swc/core'
  - bcrypt
  - core-js
  - core-js-pure
  - esbuild
  - sharp
  - workerd

overrides:
  '@babel/runtime@<7.26.10': '>=7.26.10'
  axios@>=1.0.0 <1.12.0: '>=1.12.0'
  bootstrap@>=4.0.0 <=4.6.2: '>=5.0.0'
  esbuild@<=0.24.2: '>=0.25.0'
  form-data@<2.5.4: '>=2.5.4'
  got@<11.8.5: '>=11.8.5'
  shelljs@<0.8.5: '>=0.8.5'
  tmp@<=0.2.3: '>=0.2.4'
  tough-cookie@<4.1.3: '>=4.1.3'
  vite@<=5.4.19: '>=5.4.20'
  vite@>=6.0.0 <=6.3.5: '>=6.3.6'
  webpack-dev-server@<=5.2.0: '>=5.2.1'
  ws@>=8.0.0 <8.17.1: '>=8.17.1'
