name: idpass-data-collection-dev-openspp

# Docker Compose configuration with OpenSPP integration
# Based on docker-compose.dev.yaml with OpenSPP external sync capabilities

services:
  # PostgreSQL database
  postgres:
    image: postgres:15
    restart: always
    env_file: ./.env
    volumes:
      - postgres-data-dev:/var/lib/postgresql/data
      - ../../init-reset-dbs.sh:/docker-entrypoint-initdb.d/init-reset-dbs.sh
    ports:
      - "5432:5432"
    networks:
      - datacollect-network-dev
    command: ["postgres"]

  # pgAdmin for database management (optional)
  pgadmin:
    image: dpage/pgadmin4:9
    env_file: ./.env
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - datacollect-network-dev

  # DataCollect Sync Server - Development mode with OpenSPP integration
  sync-server:
    build:
      context: ../..
      dockerfile: docker/Dockerfile
      target: backend
    develop:
      watch:
        - action: sync
          path: ../../../packages/backend
          target: /app/packages/backend
          ignore:
            - node_modules/
            - dist/
        - action: sync
          path: ../../../packages/datacollect
          target: /app/packages/datacollect
          ignore:
            - node_modules/
            - dist/
        - action: rebuild
          path: ../../../package.json
        - action: rebuild
          path: ../../../pnpm-lock.yaml
    env_file: ./.env
    ports:
      - "${SYNC_SERVER_PORT:-3000}:3000"
      - "9229:9229" # Node.js debugger port
    restart: unless-stopped
    depends_on:
      - postgres
      - openspp
    networks:
      - datacollect-network-dev
    environment:
      # Additional environment variables for OpenSPP integration
      - EXTERNAL_SYNC_ENABLED=true
      - OPENSPP_URL=http://openspp:8069
      - OPENSPP_DB=odoo
      - OPENSPP_USERNAME=admin
      - OPENSPP_PASSWORD=admin

  # Admin UI - Development mode
  admin-ui:
    build:
      context: ../..
      dockerfile: docker/Dockerfile
      target: admin-ui
    develop:
      watch:
        - action: sync
          path: ../../../packages/admin
          target: /app/packages/admin
          ignore:
            - node_modules/
            - dist/
        - action: rebuild
          path: ../../../package.json
        - action: rebuild
          path: ../../../pnpm-lock.yaml
    restart: unless-stopped
    environment:
      - VITE_API_URL=http://localhost:3000
    ports:
      - "5173:5173"
    depends_on:
      - sync-server
    networks:
      - datacollect-network-dev

  # Mobile App - Browser Development mode
  mobile-app:
    build:
      context: ../..
      dockerfile: docker/Dockerfile
      target: mobile-app
    develop:
      watch:
        - action: sync
          path: ../../../packages/mobile
          target: /app/packages/mobile
          ignore:
            - node_modules/
            - dist/
        - action: sync
          path: ../../../packages/datacollect
          target: /app/packages/datacollect
          ignore:
            - node_modules/
            - dist/
        - action: rebuild
          path: ../../../package.json
        - action: rebuild
          path: ../../../pnpm-lock.yaml
    environment:
      - VITE_DB_ENCRYPTION_PASSWORD=password
      - VITE_DEVELOP=true
      - VITE_DEBUG=true
      - VITE_FEATURE_DYNAMIC=true
    ports:
      - "8081:8081"
    depends_on:
      - sync-server
    networks:
      - datacollect-network-dev

  # OpenSPP (Odoo-based social protection platform)
  openspp:
    image: openspp/openspp:17.0
    restart: always
    env_file: ./odoo.env
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ../../../addons:/mnt/extra-addons
    ports:
      - "8069:8069"
    depends_on:
      - openspp-db
    networks:
      - datacollect-network-dev

  # PostGIS database for OpenSPP
  openspp-db:
    image: postgis/postgis:15-3.5
    restart: always
    env_file: ./odoo_postgresql.env
    volumes:
      - odoo-db-data:/var/lib/postgresql/data
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5433:5432"  # Different port to avoid conflict with main postgres
    networks:
      - datacollect-network-dev

  # Nginx reverse proxy for OpenSPP
  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - openspp
      - sync-server
      - admin-ui
    networks:
      - datacollect-network-dev

volumes:
  postgres-data-dev:
  odoo-web-data:
  odoo-db-data:

networks:
  datacollect-network-dev:
    driver: bridge
