name: ✨ Feature Request
description: Suggest a new feature or enhancement for ID PASS DataCollect
title: "[Feature]: "
labels: ["enhancement", "triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Your ideas help make ID PASS DataCollect better for everyone.

        Please provide as much detail as possible to help us understand your request.

  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we reach you for follow-up questions? (Optional)
      placeholder: your.email@example.com
    validations:
      required: false

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem would this feature solve? What is the current limitation?
      placeholder: |
        Currently, users cannot...
        This makes it difficult to...
        We need a way to...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the feature you'd like to see implemented
      placeholder: |
        I would like to see...
        The feature should work by...
        Users should be able to...
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of ID PASS DataCollect should this feature be added to?
      options:
        - Core Library (packages/datacollect)
        - Backend Server (packages/backend)
        - Admin Interface (packages/admin)
        - Mobile App (packages/mobile)
        - Docker Setup
        - Documentation
        - API/Integration
        - Data Synchronization
        - Security & Authentication
        - Other (please specify in description)
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to your work?
      options:
        - Low - Nice to have
        - Medium - Would improve workflow
        - High - Significant impact on productivity
        - Critical - Blocking current work
    validations:
      required: true

  - type: dropdown
    id: user-type
    attributes:
      label: User Type
      description: Who would benefit from this feature?
      multiple: true
      options:
        - End Users (DataCollectors)
        - System Administrators
        - Developers/Integrators
        - Data Analysts
        - Project Managers
        - External System Integrators
        - All Users

  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: Describe specific scenarios where this feature would be useful
      placeholder: |
        Scenario 1: When collecting household data...
        Scenario 2: During offline operations...
        Scenario 3: For data synchronization...
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Are there any workarounds or alternative approaches you've considered?
      placeholder: |
        Currently we work around this by...
        We considered using...
        Other options might be...
    validations:
      required: false

  - type: dropdown
    id: data-sensitivity
    attributes:
      label: Data Sensitivity Considerations
      description: Does this feature involve handling sensitive data?
      options:
        - No sensitive data involved
        - May involve personal information
        - Involves household/beneficiary data
        - Requires special privacy considerations
        - Not sure
    validations:
      required: false

  - type: textarea
    id: technical-details
    attributes:
      label: Technical Details
      description: Any technical specifications, mockups, or implementation suggestions?
      placeholder: |
        API endpoints needed...
        Database changes required...
        UI mockup available at...
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples
      placeholder: Links to similar features, screenshots, or any other relevant information
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched for existing feature requests before creating this one
          required: true
        - label: I have provided clear use cases for this feature
          required: true
        - label: I understand this feature may take time to implement and prioritize
          required: true
