name: ✨ Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Your ideas help make ID PASS DataCollect better for everyone.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem would this feature solve? What is the current limitation?
      placeholder: |
        Currently, users cannot...
        This makes it difficult to...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the feature you'd like to see implemented.
      placeholder: |
        I would like to see...
        The feature should work by...
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of ID PASS DataCollect should this feature be added to?
      options:
        - Core Library (./packages/datacollect)
        - Backend Server (./packages/backend)
        - Admin Interface (./packages/admin)
        - Mobile App (./packages/mobile)
        - Docker Setup
        - Documentation
        - API/Integration
        - Data Synchronization
        - Security & Authentication
        - Other (please specify in description)
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context or screenshots (optional).
      placeholder: Links to similar features, screenshots, or any other relevant information.
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched for existing feature requests before creating this one.
          required: true
        - label: I have provided clear use cases for this feature.
          required: true
        - label: I understand this feature may take time to implement and prioritize.
          required: true
