name: 📚 Documentation Issue
description: Report missing, unclear, or incorrect documentation
title: "[Docs]: "
labels: ["documentation", "triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping us improve our documentation! Clear documentation is essential for making ID PASS DataCollect accessible to everyone.

  - type: dropdown
    id: doc-type
    attributes:
      label: Documentation Type
      description: What type of documentation issue is this?
      options:
        - Missing documentation
        - Incorrect/outdated information
        - Unclear instructions
        - Typos/grammar issues
        - Code examples not working
        - API documentation
        - Installation/setup guide
        - Tutorial/getting started
        - Architecture documentation
        - Other
    validations:
      required: true

  - type: input
    id: page-url
    attributes:
      label: Page URL or File Path
      description: Link to the page or file path where the issue exists (optional).
      placeholder: "./docs/... or packages/datacollect/README.md"
    validations:
      required: false

  - type: textarea
    id: issue-description
    attributes:
      label: Issue Description
      description: What's wrong with the current documentation?
      placeholder: |
        The current documentation is...
        This is confusing because...
    validations:
      required: true

  - type: textarea
    id: suggested-improvement
    attributes:
      label: Suggested Improvement
      description: How should the documentation be improved? (optional)
      placeholder: |
        The documentation should instead say...
        We should add a section about...
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other information that would help us improve the documentation (optional).
      placeholder: Screenshots, links to related issues, examples from other projects, etc.
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched for existing documentation issues before creating this one.
          required: true
        - label: I have provided specific details about what needs to be improved.
          required: true
