name: ❓ Question & Support
description: Ask a question about using ID PASS DataCollect
title: "[Question]: "
labels: ["question", "support"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your question! We're here to help you use ID PASS DataCollect effectively.

        **💡 Quick Help**: Before submitting, check if your question is answered in:
        - [Documentation](https://idpass.github.io/idpass-data-collect/)
        - [Getting Started Guide](./docs/README.md)
        - [Examples](./examples/)
        - [Existing Issues](https://github.com/idpass/idpass-data-collect/issues)

  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we reach you for follow-up? (Optional)
      placeholder: your.email@example.com
    validations:
      required: false

  - type: dropdown
    id: question-type
    attributes:
      label: Question Type
      description: What kind of question is this?
      options:
        - Installation & Setup
        - Configuration
        - Usage & How-to
        - Integration with External Systems
        - Data Synchronization
        - Offline Functionality
        - Performance & Optimization
        - Best Practices
        - Troubleshooting
        - Architecture & Design
        - Development & Contributing
        - Other
    validations:
      required: true

  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: What would you like to know?
      placeholder: |
        I'm trying to understand how to...
        What's the best way to...
        How can I configure...
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component (if applicable)
      description: Which part of ID PASS DataCollect is your question about?
      options:
        - Core Library (packages/datacollect)
        - Backend Server (packages/backend)
        - Admin Interface (packages/admin)
        - Mobile App (packages/mobile)
        - Docker Setup
        - Data Synchronization
        - API Integration
        - General Usage
        - Not sure/Multiple components
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Context & Background
      description: Tell us about your use case and what you're trying to accomplish
      placeholder: |
        I'm working on a project that...
        My goal is to...
        The challenge I'm facing is...
    validations:
      required: false

  - type: input
    id: version
    attributes:
      label: Version
      description: What version of ID PASS DataCollect are you using?
      placeholder: "1.0.0"
    validations:
      required: false

  - type: dropdown
    id: environment
    attributes:
      label: Environment
      description: What environment are you working in?
      options:
        - Development
        - Staging/Testing
        - Production
        - Local Docker Setup
        - Other/Not applicable
    validations:
      required: false

  - type: textarea
    id: attempted-solutions
    attributes:
      label: What Have You Tried?
      description: What approaches have you already attempted?
      placeholder: |
        I tried following the documentation for...
        I looked at the examples and...
        I attempted to configure...
    validations:
      required: false

  - type: textarea
    id: additional-info
    attributes:
      label: Additional Information
      description: Any other details that might be helpful
      placeholder: Error messages, configuration files, screenshots, etc.
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have checked the documentation and examples
          required: true
        - label: I have searched for similar questions in existing issues
          required: true
        - label: I have provided enough context for others to understand my question
          required: true
        - label: I understand that this is a community project and responses may take time
          required: true
