FROM node:22-bookworm-slim AS base
RUN npm i -g pnpm

FROM base AS build
WORKDIR /app
COPY . .
RUN pnpm -r install --frozen-lockfile
RUN pnpm run build:datacollect

FROM base as admin-ui
WORKDIR /app
COPY --from=build /app .
EXPOSE 5173
CMD ["pnpm", "run", "dev:admin"]

