version: '3.8'

# Example Docker Compose configuration with OpenSPP integration
# This demonstrates how to set up the full stack with external sync capabilities

services:
  # HDM Sync Server - Main application
  sync-server:
    platform: linux/amd64
    image: "hdm-sync-server:latest"
    build:
      context: ..
      dockerfile: docker/Dockerfile
    user: "node"
    working_dir: /home/node/app
    env_file: ./.env
    ports:
      - "3000:3000"
    # Command is set in Dockerfile CMD
    restart: always
    depends_on:
      - postgres
      - openspp
    networks:
      - hdm-network
    environment:
      # Additional environment variables for OpenSPP integration
      - EXTERNAL_SYNC_ENABLED=true
      - OPENSPP_URL=http://openspp:8069
      - OPENSPP_DB=odoo
      - OPENSPP_USERNAME=admin
      - OPENSPP_PASSWORD=admin

  # PostgreSQL database for HDM Sync Server
  postgres:
    platform: linux/amd64
    image: postgres:15
    restart: always
    env_file: ./postgresql.env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - hdm-network

  # Admin UI (Vue.js application)
  admin-ui:
    platform: linux/amd64
    image: "hdm-admin-ui:latest"
    build:
      context: ..
      dockerfile: docker/Dockerfile.admin
    ports:
      - "5173:80"
    environment:
      - VITE_API_URL=http://sync-server:3000
    depends_on:
      - sync-server
    networks:
      - hdm-network

  # OpenSPP (Odoo-based social protection platform)
  openspp:
    platform: linux/amd64
    image: openspp/openspp:17.0
    restart: always
    env_file: ./odoo.env
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ../addons:/mnt/extra-addons
    ports:
      - "8069:8069"
    depends_on:
      - openspp-db
    networks:
      - hdm-network

  # PostGIS database for OpenSPP
  openspp-db:
    platform: linux/amd64
    image: postgis/postgis:15-3.5
    restart: always
    env_file: ./odoo_postgresql.env
    volumes:
      - odoo-db-data:/var/lib/postgresql/data
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5433:5432"  # Different port to avoid conflict with main postgres
    networks:
      - hdm-network

  # Nginx reverse proxy for OpenSPP
  nginx:
    platform: linux/amd64
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - openspp
      - sync-server
      - admin-ui
    networks:
      - hdm-network

volumes:
  postgres-data:
  odoo-web-data:
  odoo-db-data:

networks:
  hdm-network:
    driver: bridge