version: "3.8"

services:
  # Nginx reverse proxy
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - sync-server
      - admin-ui
    networks:
      - hdm-network

  # HDM Sync Server - Main application
  sync-server:
    image: "hdm-sync-server:latest"
    build:
      context: ..
      dockerfile: docker/Dockerfile
    user: "node"
    working_dir: /home/node/app
    env_file: ./.env
    restart: always
    depends_on:
      - postgres
    networks:
      - hdm-network

  # PostgreSQL database for HDM Sync Server
  postgres:
    image: postgres:15
    restart: always
    env_file: ./postgresql.env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - hdm-network

  # Admin UI (Vue.js application)
  admin-ui:
    image: "hdm-admin-ui:latest"
    build:
      context: ..
      dockerfile: docker/Dockerfile.admin
      args:
        - VITE_API_URL=/sync
    depends_on:
      - sync-server
    networks:
      - hdm-network

volumes:
  postgres-data:

networks:
  hdm-network:
    driver: bridge
