FROM node:22-bookworm-slim AS base
RUN npm i -g pnpm

FROM base AS build
WORKDIR /app
COPY . .
RUN pnpm -r install --frozen-lockfile
RUN pnpm run build:datacollect
RUN pnpm --filter @idpass/adapter-openspp --filter @idpass/adapter-openfn --filter @idpass/adapter-mock build
RUN pnpm run build:backend

FROM base as backend
WORKDIR /app
COPY --from=build /app .
EXPOSE 3000
CMD ["node", "packages/backend/dist/index.js"]

