services:
  # HDM Sync Server - Development mode
  sync-server:
    image: node:20-bookworm-slim
    working_dir: /packages
    env_file: ./.env
    environment:
      - NODE_ENV=development
      - NODE_OPTIONS=--max-old-space-size=4096
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "3000:3000"
      - "9229:9229" # Node.js debugger port
    volumes:
      - ../packages/backend:/packages/backend
      - ../packages/datacollect:/packages/datacollect
      - /packages/datacollect/node_modules
      - /packages/backend/node_modules
    command: |
      sh -c "
        mkdir -p /packages/datacollect/node_modules &&
        mkdir -p /packages/backend/node_modules &&
        chown -R node:node /packages/datacollect/node_modules &&
        chown -R node:node /packages/backend/node_modules &&
        su node -c '
          cd datacollect &&
          npm install &&
          npm run build &&
          cd ../backend &&
          npm install ../datacollect &&
          npm install &&
          npm run dev -- --inspect=0.0.0.0:9229
        '
      "
    restart: unless-stopped
    depends_on:
      - postgres
    networks:
      - hdm-network

  # PostgreSQL database
  postgres:
    image: postgres:15
    restart: always
    env_file: ./postgresql.env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - hdm-network

  # Admin UI - Development mode
  admin-ui:
    image: node:20-bookworm-slim
    working_dir: /app
    environment:
      - VITE_API_URL=http://localhost:3000
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "5173:5173"
    volumes:
      - ../packages/admin:/app
      - /app/node_modules
    command: |
      sh -c "
        mkdir -p /app/node_modules &&
        chown -R node:node /app/node_modules &&
        su node -c '
          npm install &&
          npm run dev -- --host 0.0.0.0
        '
      "
    depends_on:
      - sync-server
    networks:
      - hdm-network

  # Mobile App - Browser Development mode
  mobile-app:
    image: node:20-bookworm-slim
    working_dir: /app
    environment:
      - VITE_DB_ENCRYPTION_PASSWORD=password
      - VITE_DEVELOP=true
      - VITE_DEBUG=true
      - VITE_FEATURE_DYNAMIC=true
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "8081:8081"
    volumes:
      - ../packages/mobile:/app/mobile
      - ../packages/datacollect:/app/datacollect
      - /app/datacollect/node_modules
      - /app/mobile/node_modules
    command: |
      sh -c "
        mkdir -p /app/mobile/node_modules &&
        mkdir -p /app/datacollect/node_modules &&
        chown -R node:node /app/mobile/node_modules &&
        chown -R node:node /app/datacollect/node_modules &&
        su node -c '
          cd datacollect &&
          npm install &&
          cd ../mobile &&
          npm install ../datacollect &&
          npm install &&
          npm run dev -- --host 0.0.0.0
        '
      "

  # pgAdmin for database management (optional)
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - hdm-network

volumes:
  postgres-data:

networks:
  hdm-network:
    driver: bridge
